name: push_conf_daily

env:
  PYTHON_VERSION: "3.8" # set this to the Python version to use
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  issues:
    types:
      - labeled

  schedule:
    - cron: '0 4 * * *' # 每天 UTC 时间 04:00 触发, 即上海时间12点

jobs:
  daily-push:
    if: github.event.label.name == 'push conf test'
    runs-on: ubuntu-latest
    env:
      SERVERCHAN_API_KEY: ${{ secrets.SERVERCHAN_API_KEY }}
      CAIYUN_TOKEN: ${{ secrets.CAIYUN_TOKEN }}
      CONF_URL: ${{ secrets.CONF_URL }}
      FEISHU_URL: ${{ secrets.FEISHU_URL }}
      INTERVAL: 5
      LIMITS: 10
      ERROR_LIMITS: 5

    permissions:
      issues: write
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: pip install tqdm requests


      - name: PUSH CONF DAILY
        run: |
          python conf.py
          python render.py
        
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [ -z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
          else
             git commit -m "chore: update confs" -a
             echo "::set-output name=push::true"
          fi
        shell: bash

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
